### ISSUE TITLE
AWS IoT Deploy 実行後、EC2側でエラーになる

### ISSUE THREAD

**Issue by satour** [enebular/enebular-agent-aws-iot#4]
以前は発生しなかった。EC2側の設定だと思うが、設定手順が確立されていない（AWS IoTのアップデートに追従していない？）為、状況要調査。

```
# enebular の画面では、Successfully Deployed のメッセージ表示後

$ ./node_modules/.bin/enebular-agent-aws-iot run ./node_modules/.bin/node-red -s settings.js
>> connected to AWS IoT
* update the device's power state to ON...
* received flows definition =>  [{"type":"tab","id":"d38ef6bc.bf8c48","label":"Flow 1"},{"id":"d95e7e20.3e833","type":"inject","z":"d38ef6bc.bf8c48","name":"","topic":"","payload":"AWS IoT経由でデプロイしました！2","payloadType":"str","repeat":"","crontab":"","once":false,"x":240,"y":80,"wires":[["597cfabd.7a21e4"]]},{"id":"597cfabd.7a21e4","type":"debug","z":"d38ef6bc.bf8c48","name":"","active":true,"console":"false","complete":"false","x":490,"y":80,"wires":[]}]
* received creds definition =>  {}
* received packages definition =>  {}
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at handlePackagesStateChange (/home/ubuntu/enebular/node_modules/enebular-agent-aws-iot/index.js:156:20)
    at ThingShadowsClient.<anonymous> (/home/ubuntu/enebular/node_modules/enebular-agent-aws-iot/index.js:103:7)
    at ThingShadowsClient.g (events.js:260:16)
    at emitMany (events.js:108:13)
    at ThingShadowsClient.emit (events.js:182:7)
    at ThingShadowsClient._handleMessages (/home/ubuntu/enebular/node_modules/enebular-agent-aws-iot/node_modules/aws-iot-device-sdk/thing/index.js:318:12)
    at DeviceClient.<anonymous> (/home/ubuntu/enebular/node_modules/enebular-agent-aws-iot/node_modules/aws-iot-device-sdk/thing/index.js:355:21)
```

**Comment by satour** [comment]
- 以前は発生していなかった事象。
- aws-iot-device-sdk-js のバージョンアップの影響？ 6月に aws-iot-device-sdk-js のメジャーバージョンアップが行われている。8月にさらにマイナーバージョンアップが行われている。
- デプロイ後、node-red のプロセスが残ったままになる。kill しないと、node-redを再起動できない

**Comment by satour** [comment]
package.json
```
"dependencies": {
    "aws-iot-device-sdk": "^1.0.9"
  }
```
なので、メジャーアップデートはしないことになっている。
1系では fca6f8c52f5870957dac0f9c683e023251bec66f の `1.0.14` が最新
